# Workflow name
name: Project CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout this repository.
        uses: actions/checkout@v2

      - name: CMAKE creates build files.
        run: |
          mkdir out
          cmake -S . -B ./out/ -DCMAKE_BUILD_TYPE=Release

      - name: CMAKE build project.
        run: cmake --build ./out/

